<?php

namespace ChamadoBundle\Repository;

/**
 * ChamadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChamadoRepository extends \Doctrine\ORM\EntityRepository
{
}
